const USER = {
  VERIFY_USER_STARTING: 'VERIFY_USER_STARTING',
  VERIFY_USER_DONE: 'VERIFY_USER_DONE',
  VERIFY_USER_ERROR: 'VERIFY_USER_ERROR',

  LOGIN_USER_STARTING: 'LOGIN_USER_STARTING',
  LOGIN_USER_DONE: 'LOGIN_USER_DONE',
  LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',

  LOGOUT_USER_STARTING: 'LOGOUT_USER_STARTING',
  LOGOUT_USER_DONE: 'LOGOUT_USER_DONE',
  LOGOUT_USER_ERROR: 'LOGOUT_USER_ERROR',
}

export {
  USER
}